name: API CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'client/**'
    - '.github/workflows/client.yml'
  pull_request:
    paths-ignore:
    - 'client/**'
    - '.github/workflows/client.yml'

env:
  SONAR_TOKEN: ${{ secrets.SONAR_ACCESS_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://npm.play-consult.net

    - name: Configure NPM
      run: |
        echo "//npm.play-consult.net/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
        echo 'registry=https://npm.play-consult.net' >> .npmrc
        echo '//npm.play-consult.net/:always-auth = true' >> .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

    - run: yarn install
    - run: yarn test


    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1

    # Runs a single command using the runners shell
    - name: Scan API with SonarQube
      run: sonar-scanner
         -Dsonar.login=${{ secrets.SONAR_ACCESS_TOKEN }}
         -Dsonar.host.url=https://sonarqube.play-consult.net
